name: fbuids
services:
  app:
    build: .
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/fbid_phones
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fbuid.rule=Host(`fbuid.nestproxy.com`)"
      - "traefik.http.routers.fbuid.entrypoints=web"
      - "traefik.http.services.fbuid.loadbalancer.server.port=3000"
    networks:
      my_custom_network:
        ipv4_address: ${FBUID_APP_IP:-10.0.188.12}

  mongo:
    image: mongo:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - mongodb-data:/data/db
    networks:
      my_custom_network:
        ipv4_address: ${FBUID_MONGO_IP:-10.0.188.10}

volumes:
  mongodb-data:

networks:
  my_custom_network:
    external: true
