version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    extra_hosts:
      - host.docker.internal:host-gateway
  mongo:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  mongodb-data:
